FROM node:lts-bullseye

USER root
WORKDIR /app/

COPY package.json yarn.lock ./docker/docker_entry.sh ./docker/install.sh ./

RUN sed -i s@/deb.debian.org/@/mirrors.ustc.edu.cn/@g /etc/apt/sources.list \
  && sed -i s@/security.debian.org/@/mirrors.ustc.edu.cn/@g /etc/apt/sources.list \
  && bash install.sh \
  && rm install.sh

EXPOSE 8080

ENTRYPOINT ["/app/docker_entry.sh"]
CMD [""]
